const products = [
  { product_id: 1000, product_name: 'Fish Fingers', unit_price: 2.55, unit_quantity: '500 gram', in_stock: 1500, category: 'Frozen Foods', image:"./gridpictures/fishfingers500g.avif" },
  { product_id: 1001, product_name: 'Fish Fingers', unit_price: 5.00, unit_quantity: '1000 gram', in_stock: 750, category: 'Frozen Foods', image: './gridpictures/fishfingers1kg.webp' },
  { product_id: 1002, product_name: 'Hamburger Patties', unit_price: 2.35, unit_quantity: 'Pack 10', in_stock: 1200, category: 'Frozen Foods', image: './gridpictures/hamburgerpatties.avif' },
  { product_id: 1003, product_name: 'Shelled Prawns', unit_price: 6.90, unit_quantity: '250 gram', in_stock: 300, category: 'Frozen Foods', image: './gridpictures/shelledprawns.avif' },
  { product_id: 1004, product_name: 'Tub Ice Cream', unit_price: 1.80, unit_quantity: 'I Litre', in_stock: 800, category: 'Frozen Foods', image: './gridpictures/icecream1.avif' },
  { product_id: 1005, product_name: 'Tub Ice Cream', unit_price: 3.40, unit_quantity: '2 Litre', in_stock: 1200, category: 'Frozen Foods', image: './gridpictures/icecream2l.webp' },
  { product_id: 2000, product_name: 'Panadol', unit_price: 3.00, unit_quantity: 'Pack 24', in_stock: 2000, category: 'Health & Pharmacy', image: './gridpictures/panadolsmall.webp' },
  { product_id: 2001, product_name: 'Panadol', unit_price: 5.50, unit_quantity: 'Bottle 50', in_stock: 1000, category: 'Health & Pharmacy', image: './gridpictures/panadolbig.avif' },
  { product_id: 2002, product_name: 'Bath Soap', unit_price: 2.60, unit_quantity: 'Pack 6', in_stock: 500, category: 'Household Essentials', image: './gridpictures/bathsoap.avif' },
  { product_id: 2003, product_name: 'Garbage Bags Small', unit_price: 1.50, unit_quantity: 'Pack 10', in_stock: 500, category: 'Household Essentials', image: './gridpictures/smallbags.webp' },
  { product_id: 2004, product_name: 'Garbage Bags Large', unit_price: 5.00, unit_quantity: 'Pack 50', in_stock: 300, category: 'Household Essentials', image: './gridpictures/largebags.webp' },
  { product_id: 2005, product_name: 'Washing Powder', unit_price: 4.00, unit_quantity: '1000 gram', in_stock: 800, category: 'Household Essentials', image: './gridpictures/washingpowder.avif' },
  { product_id: 2006, product_name: 'Laundry Bleach', unit_price: 3.55, unit_quantity: '2 Litre Bottle', in_stock: 500, category: 'Household Essentials', image: './gridpictures/laundrybleach.avif' },
  { product_id: 3000, product_name: 'Cheddar Cheese', unit_price: 8.00, unit_quantity: '500 gram', in_stock: 1000, category: 'Fresh Foods', image: '/gridpictures/cheddar500g.avif'},
  { product_id: 3001, product_name: 'Cheddar Cheese', unit_price: 15.00, unit_quantity: '1000 gram', in_stock: 1000, category: 'Fresh Foods', image: './gridpictures/cheese1kg.avif' },
  { product_id: 3002, product_name: 'T Bone Steak', unit_price: 7.00, unit_quantity: '1000 gram', in_stock: 200, category: 'Fresh Foods', image: './gridpictures/tbone.avif' },
  { product_id: 3003, product_name: 'Navel Oranges', unit_price: 3.99, unit_quantity: 'Bag 20', in_stock: 200, category: 'Fruits & Vegetables', image: './gridpictures/navel.avif' },
  { product_id: 3004, product_name: 'Bananas', unit_price: 1.49, unit_quantity: 'Kilo', in_stock: 400, category: 'Fruits & Vegetables', image: './gridpictures/bananas.avif' },
  { product_id: 3005, product_name: 'Peaches', unit_price: 2.99, unit_quantity: 'Kilo', in_stock: 500, category: 'Fruits & Vegetables', image: './gridpictures/peach.png' },
  { product_id: 3006, product_name: 'Grapes', unit_price: 3.50, unit_quantity: 'Kilo', in_stock: 200, category: 'Fruits & Vegetables', image: './gridpictures/grapes.webp' },
  { product_id: 3007, product_name: 'Apples', unit_price: 1.99, unit_quantity: 'Kilo', in_stock: 500, category: 'Fruits & Vegetables', image: './gridpictures/apples.webp' },
  { product_id: 4000, product_name: 'Earl Grey Tea Bags', unit_price: 2.49, unit_quantity: 'Pack 25', in_stock: 1200, category: 'Beverages & Confectionery', image: './gridpictures/tea.avif' },
  { product_id: 4001, product_name: 'Earl Grey Tea Bags', unit_price: 7.25, unit_quantity: 'Pack 100', in_stock: 1200, category: 'Beverages & Confectionery', image: './gridpictures/tea100.avif' },
  { product_id: 4002, product_name: 'Earl Grey Tea Bags', unit_price: 13.00, unit_quantity: 'Pack 200', in_stock: 800, category: 'Beverages & Confectionery', image: './gridpictures/tea200.avif' },
  { product_id: 4003, product_name: 'Instant Coffee', unit_price: 2.89, unit_quantity: '200 gram', in_stock: 500, category: 'Beverages & Confectionery', image: './gridpictures/coffee.avif' },
  { product_id: 4004, product_name: 'Instant Coffee', unit_price: 5.10, unit_quantity: '500 gram', in_stock: 500, category: 'Beverages & Confectionery', image: './gridpictures/coffee500.avif' },
  { product_id: 4005, product_name: 'Chocolate Bar', unit_price: 2.50, unit_quantity: '500 gram', in_stock: 300, category: 'Beverages & Confectionery', image: './gridpictures/choc.jpeg' },
  { product_id: 5000, product_name: 'Dry Dog Food', unit_price: 5.95, unit_quantity: '5 kg Pack', in_stock: 400, category: 'Pet Supplies', image: './gridpictures/dogfood5kg.jpg' },
  { product_id: 5001, product_name: 'Dry Dog Food', unit_price: 1.95, unit_quantity: '1 kg Pack', in_stock: 400, category: 'Pet Supplies', image: './gridpictures/dogfood1kg.avif' },
  { product_id: 5002, product_name: 'Bird Food', unit_price: 3.99, unit_quantity: '500g packet', in_stock: 200, category: 'Pet Supplies', image: './gridpictures/birdfood.avif' },
  { product_id: 5003, product_name: 'Cat Food', unit_price: 2.00, unit_quantity: '500g tin', in_stock: 200, category: 'Pet Supplies', image: './gridpictures/catfood.avif' },
  { product_id: 5004, product_name: 'Fish Food', unit_price: 3.00, unit_quantity: '500g packet', in_stock: 200, category: 'Pet Supplies', image: './gridpictures/fishfood.avif' }
];